Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-07, with the labels that each got.

#352 [DialogMusicInfo] improved animation
  1080i/Includes_Animations.xml
  1080i/Includes_DialogMusicInfo.xml
  1080i/Includes_Lists.xml
Labels: Improvement, Kodi 19

#353 [View 50 Language] minor adjustments to view 50, string corrections
  1080i/Includes_Labels.xml
  1080i/MyVideoNav.xml
  1080i/View_50_List.xml
  shortcuts/overrides.xml
Labels: Improvement, Kodi 19

#355 [Code] cleanup
  1080i/Includes_Home.xml
  1080i/Includes_NowPlaying.xml
  shortcuts/template.xml
Labels: Improvement, Kodi 19

#356 [Cleanup] duplicate option
  1080i/SkinSettings.xml
Labels: Improvement, Kodi 19

#346 [SkinSettings] logo added
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Feature, Improvement, Kodi 19, Review

#357 [Localization] french translate
  language/resource.language.fr_fr/strings.po
Labels: Kodi 19, Language

#359 [CoreElec] design fit to AZR - part2
  1080i/service-CoreELEC-Settings-mainWindow.xml
  media/elec/bluetooth.png
  media/elec/connected.png
  media/elec/ethernet.png
  media/elec/favorites.png
  media/elec/key.png
  media/elec/unlock.png
  media/elec/vpn.png
  media/elec/wlan.png
Labels: Improvement, Kodi 19

#360 [Weather] improved code and animation conditions
  1080i/Includes_Animations.xml
  1080i/Includes_Furniture.xml
Labels: Improvement, Kodi 19, Review

#363 [Fix] fallback image OSD music or Slideshow
  1080i/MusicVisualisation.xml
Labels: Fix, Kodi 19, Review

#366 [Code] improvements, cleanup
  1080i/Custom_AutoAS.xml
  1080i/Custom_MusicSettings.xml
  1080i/DialogKeyboard.xml
  1080i/Includes.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
  shortcuts/overrides.xml
Labels: Improvement, Kodi 19

#367 [MusicOSD] added scrollbar to music osd
  1080i/Includes_Furniture.xml
  1080i/MusicOSD.xml
Labels: Feature, Kodi 19

#365 [Music Visualisation] improvement
  1080i/MusicVisualisation.xml
Labels: Improvement, Kodi 19

#368 [Homemenu Animation] added option to slide out home menu items, if not used/focused
  1080i/DialogButtonMenu.xml
  1080i/Home.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Feature, Kodi 19, Review

#371 [OSD Settings] improvements
  1080i/Custom_MusicSettings.xml
  1080i/Custom_VideoSetting.xml
  1080i/Includes_Defs.xml
  1080i/MusicOSD.xml
  1080i/MusicVisualisation.xml
  language/resource.language.en_gb/strings.po
Labels: Improvement, Kodi 19

#372 [Show now playing] improvement
  1080i/Includes.xml
Labels: Improvement, Kodi 19

#373 [MyVideo/MusicNav Code] improvements, cleanup
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Defs.xml
  1080i/Includes_OSD.xml
  1080i/MyMusicNav.xml
  1080i/MyVideoNav.xml
Labels: Improvement, Kodi 19

#374 [MyVideo/MusicNav] use short descriptions
  1080i/Custom_MusicSettings.xml
  1080i/Custom_VideoSetting.xml
  1080i/DialogSeekBar.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
  1080i/MyMusicNav.xml
  1080i/MyVideoNav.xml
  1080i/View_501_Modern_Fanart.xml
  language/resource.language.de_de/strings.po
  language/resource.language.en_gb/strings.po
Labels: Improvement, Kodi 19, Language, Review

#375 [MusicVisualisation] improved animations
  1080i/Includes_NowPlaying.xml
  1080i/MusicVisualisation.xml
Labels: Improvement, Kodi 19, Review

#378 [NowPlaying] option to enable tracklist instead artist/albuminfo for music
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/SkinSettings.xml
Labels: Feature, Kodi 19

#377 [Fix] background / fallback image not display on focus 2011
  1080i/Includes.xml
Labels: Fix, Kodi 19

#380 [NowPlaying] added forward/rewind status icons
  1080i/Includes_Defs.xml
  1080i/Includes_NowPlaying.xml
  media/progress/ff.png
  media/progress/rw.png
Labels: Improvement, Kodi 19, Review

#381 [Code] improvements, cleanup
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
  language/resource.language.de_de/strings.po
  language/resource.language.en_gb/strings.po
Labels: Improvement, Kodi 19

#382 minor adjustment
  1080i/SettingsProfile.xml
  1080i/SettingsSystemInfo.xml
Labels: Improvement, Kodi 19

#385 [Code] improvements, cleanup
  1080i/DialogPlayerProcessInfo.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/SettingsProfile.xml
  1080i/View_55_Wall.xml
  1080i/script-embuary-video.xml
Labels: Code Fix, Improvement, Kodi 19

#397 [DialogVideoInfo] minor adjustments
  1080i/script-embuary-person.xml
  1080i/script-embuary-video.xml
Labels: Improvement, Kodi 19

#393 [Colorpicker] improvements to focused items
  1080i/script-skin_helper_service-ColorPicker.xml
Labels: Improvement, Kodi 19

#399 [MyMusicPlaylistEditor] improvements
  1080i/MyMusicPlaylistEditor.xml
Labels: Improvement, Kodi 19

#402 [Code] update
  1080i/Includes_BlurSettings.xml
  1080i/Includes_CustomSettings_Items.xml
  1080i/Includes_Defs.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
Labels: Kodi 19, Update

#404 [Views 510, 52x Netflix] added option to disable netflix fanart window in views 510, 52x
  1080i/Includes.xml
  1080i/MyVideoNav.xml
Labels: Improvement, Kodi 19

#401 [Litebox] use litebox for blur
  1080i/Custom_1297_Blur.xml
  1080i/Custom_DialogBusy.xml
  1080i/Custom_DialogCustomSettings.xml
  1080i/Custom_DialogNumeric.xml
  1080i/Custom_Overlay.xml
  1080i/Includes.xml
  1080i/Includes_BlurSettings.xml
  1080i/Includes_CustomSettings_Items.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Furniture.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
  addon.xml
  language/resource.language.en_gb/strings.po
Labels: Feature, Kodi 19, Review

#398 [CoreELEC LibreELEC Settings] improvements to settings window
  1080i/service-CoreELEC-Settings-mainWindow.xml
  1080i/service-LibreELEC-Settings-mainWindow.xml
Labels: Improvement, Kodi 19, Review

#406 [Code] update
  1080i/DialogSeekBar.xml
  1080i/Includes.xml
  1080i/Includes_OSD.xml
  1080i/VideoOSD.xml
Labels: Kodi 19, Update

#407 [Indicators] fixed issue with reloaded indicators
  1080i/Includes_Defs.xml
  1080i/Includes_Images.xml
  1080i/Includes_Labels.xml
Labels: Fix, Kodi 19

#408 Translations update from Weblate
  language/resource.language.fr_fr/strings.po
Labels: Kodi 19, Weblate

#400 [OSD Seekbar] show seekbar if osd is shown
  1080i/Custom_VideoSetting.xml
  1080i/DialogSeekBar.xml
  1080i/Includes.xml
  1080i/Includes_OSD.xml
  1080i/VideoOSD.xml
Labels: Improvement, Kodi 19, Review

#409 [Homemenu Animation] added option to slide out home menu items, if no…
  1080i/Includes.xml
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
Labels: Feature, Kodi 19, Review

#411 Translations update from Weblate
  language/resource.language.it_it/strings.po
Labels: Kodi 19, Weblate

#412 [OSD Animations] improvements
  1080i/DialogSeekBar.xml
Labels: Improvement, Kodi 19

#415 [SkinSettings] fixed color of AZR logo
  1080i/SkinSettings.xml
Labels: Fix, Kodi 19

#416 [OSD] improvements for more consistency
  1080i/DialogSeekBar.xml
  1080i/Includes.xml
  1080i/Includes_OSD.xml
  1080i/MusicVisualisation.xml
  1080i/VideoOSD.xml
  colors/defaults.xml
Labels: Improvement, Kodi 19

#418 [SkinSettings] changed settings for next update, minor adjustments
  1080i/Custom_1297_Blur.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
  addon.xml
Labels: Improvement, Kodi 19

#421 [Addon] infos changed
  addon.xml
Labels: Improvement, Kodi 19

#422 [Code, Diffuse Images] improved overall quality
  1080i/Includes_Defs.xml
  1080i/Includes_DialogPVRInfo.xml
  1080i/Includes_Home.xml
  1080i/Includes_NowPlaying.xml
  1080i/Includes_PVR.xml
  1080i/MyPVRGuide.xml
  1080i/View_504_Netflix.xml
  1080i/View_506_Slider.xml
  1080i/View_50_List.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_515_SideCards.xml
  1080i/View_516_SeasonsInfo.xml
  1080i/View_51_BigWide.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  1080i/View_52_BigList.xml
  1080i/View_53_Poster.xml
  1080i/View_56_MediaInfo.xml
  1080i/View_57_ExtraInfo.xml
  1080i/View_58_Cards.xml
  1080i/script-embuary-person.xml
  1080i/script-embuary-video.xml
  1080i/script-globalsearch.xml
  media/common/box21.png
  media/diffuse/cards_top.png
  media/diffuse/widgetbanner_new.png
  media/diffuse/widgetbanner_small.png
  media/diffuse/widgetfanart_new.png
  media/diffuse/widgetfanart_top.png
  media/diffuse/widgetfanart_topright.png
  media/diffuse/widgetposter_left.png
  media/diffuse/widgetposter_new.png
  media/diffuse/widgetsquare_new.png
Labels: Improvement, Kodi 19

#424 [Music Playlist OSD] more simple playlist
  1080i/MusicOSD.xml
Labels: Improvement, Kodi 19, Review

#426 Translations update from Weblate
  language/resource.language.it_it/strings.po
Labels: Kodi 19, Weblate

#430 [Files] file renamed
  media/flags/color/resolution/4K.png
Labels: Code Fix, Kodi 19

#433 [Code] improvements, minor adjustments
  1080i/Custom_Ok.xml
  1080i/Custom_SetHomeViewtype.xml
  1080i/Includes_Defs.xml
  1080i/VideoOSDBookmarks.xml
  1080i/script-skinshortcuts.xml
Labels: Improvement, Kodi 19

#431 [Home Vertical] Hide completely menu when slide out
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
Labels: Improvement, Kodi 19, Review

#427 [Music Video OSD] improvements
  1080i/Includes_OSD.xml
  1080i/MusicOSD.xml
  media/osd/noshuffle.png
  media/osd/repeat-off.png
Labels: Improvement, Kodi 19, Review

#434 [SkinSettings] improvement
  1080i/SkinSettings.xml
Labels: Improvement, Kodi 19

#429 [MusicOSD] improvements playlist access
  1080i/Custom_MusicSettings.xml
  1080i/Custom_SetVis.xml
  1080i/Includes_Labels.xml
  1080i/Includes_OSD.xml
  language/resource.language.de_de/strings.po
  language/resource.language.en_gb/strings.po
Labels: Improvement, Kodi 19, Review
