Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-08, with the labels that each got.

#437 [Skin Settings] fixed issue in supported addons tab
  1080i/Includes_Defs.xml
Labels: Fix, Kodi 19

#439 [Background Skin Settings] removed fullsize fanart settings limitation
  1080i/Includes.xml
  1080i/Includes_CustomSettings_Items.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
Labels: Improvement, Kodi 19

#441 [Views Scrollbars] improved overall consistency
  1080i/Includes_Furniture.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_503_Poster_Square.xml
  1080i/View_507_Fanart.xml
  1080i/View_509_Shift.xml
  1080i/View_510_Minimal.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_514_Albums.xml
  1080i/View_515_SideCards.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  1080i/View_523_Minimal_V2_Music.xml
  1080i/View_524_Minimal_V2_Seasons.xml
  1080i/View_526_SeasonsInfo_V2.xml
Labels: Improvement, Kodi 19, Review

#443 [Textures] fixed filename and path - 2
  1080i/Defaults.xml
Labels: Fix, Kodi 19

#444 [Login Screen] improvements
  1080i/LoginScreen.xml
  media/other_textures/circle.png
  shortcuts/powermenu.DATA.xml
Labels: Improvement, Kodi 19

#445 [Home Header] Improvements
  1080i/Includes_Furniture.xml
Labels: Improvement, Kodi 19, Review

#447 [DialogInfo Container Items] added container items and position to im…
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/script-embuary-person.xml
  1080i/script-embuary-video.xml
Labels: Feature, Kodi 19

#455 [Flag Mpaa] Fix and consistency for French
  1080i/Includes.xml
Labels: Kodi 19, Improvement

#454 [Startup] patch 3
  1080i/Custom_Startup.xml
  1080i/LoginScreen.xml
  1080i/Startup.xml
  media/other_textures/circle_full.png
Labels: Kodi 19, Fix, Review

#446 [Home Header] Improvements "TV Shows" default
  1080i/Includes_Furniture.xml
Labels: Kodi 19, Improvement, Review

#458 [Home Header] Improvements "Videos"
  1080i/Includes_Furniture.xml
Labels: Kodi 19, Improvement

#452 [Home Header] Improvements "Settings"
  1080i/Includes_Furniture.xml
Labels: Kodi 19, Improvement, Review

#457 [Focus Items] added setting to zoom/glow focused items
  1080i/Includes_Animations.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
  1080i/MyPics.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/View_500_Thumbnails.xml
  1080i/View_504_Netflix.xml
  1080i/View_505_Wall_Square.xml
  1080i/View_509_Shift.xml
  1080i/View_50_List.xml
  1080i/View_510_Minimal.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_513_Shifted.xml
  1080i/View_514_Albums.xml
  1080i/View_517_WallSmall.xml
  1080i/View_520_Minimal.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  1080i/View_524_Minimal_V2_Seasons.xml
  1080i/View_526_SeasonsInfo_V2.xml
  1080i/View_55_Wall.xml
  1080i/View_59_BannerWall.xml
  language/resource.language.en_gb/strings.po
  media/common/gradient-selectbox2.png
  media/common/selectbox2.png
Labels: Kodi 19, Feature, Review

#463 [Code] improvements
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
Labels: Kodi 19, Code Fix

#464 [View 56] fixed list issue
  1080i/View_56_MediaInfo.xml
Labels: Kodi 19, Improvement

#450 [Home Header] Improvements "Favourites"
  1080i/Home.xml
  1080i/Includes_Furniture.xml
  1080i/SkinSettings.xml
Labels: Kodi 19, Improvement, Review

#451 [Home Header] Improvements "Playlist"
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_Lists.xml
Labels: Kodi 19, Improvement

#469 [Textbox Autoscroll] improved autoscrolling of textboxes/titles
  1080i/Defaults.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_DialogMusicInfo.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_Home.xml
  1080i/Includes_OSD.xml
  1080i/SkinSettings.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_507_Fanart.xml
  1080i/View_510_Minimal.xml
  1080i/View_51_BigWide.xml
  1080i/View_520_Minimal.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_523_Minimal_V2_Music.xml
  1080i/script-embuary-video.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Improvement, Review

#471 [mpaa] improvement french
  1080i/Includes.xml
Labels: Kodi 19, Improvement

#475 [Screen Settings Calibration] improvements
  1080i/SettingsScreenCalibration.xml
  media/other_textures/calibratepixelratio.png
Labels: Kodi 19, Improvement

#476 [View 521] added alternative layout setting
  1080i/Includes.xml
  1080i/MyVideoNav.xml
  1080i/View_521_Minimal_V2.xml
Labels: Kodi 19, Feature

#477 [View 527] added view 527
  1080i/Custom_SetViewtype.xml
  1080i/Includes.xml
  1080i/Includes_Images.xml
  1080i/MyVideoNav.xml
  1080i/View_527_List_V2.xml
  extras/views/527.jpg
  extras/views/light/527.jpg
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Feature

#478 [View 527] improvements
  1080i/Includes_Labels.xml
  1080i/MyVideoNav.xml
  1080i/View_527_List_V2.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Improvement

#482 Translations update from Weblate
  language/resource.language.fr_fr/strings.po
Labels: Kodi 19, Weblate

#484 [Code] update
  1080i/Custom_Overlay.xml
  language/resource.language.fr_fr/strings.po
Labels: Kodi 19, Update
