Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-04, with the labels that each got.

#162 [Views] added auto scrolling titles for a few views
  1080i/SkinSettings.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_507_Fanart.xml
  1080i/View_510_Minimal.xml
  1080i/View_51_BigWide.xml
  1080i/View_520_Minimal.xml
  1080i/View_521_Minimal_V2.xml
  language/English/strings.po
Labels: Feature, Kodi 19

#165 [View 516] fixed issue with new watched indicators
  1080i/Includes_Home.xml
  1080i/View_516_SeasonsInfo.xml
Labels: Fix, Kodi 19

#163 Extended "SubHeaderLabel" for TVShows, Movies, PVR and Weather
  1080i/Includes_Furniture.xml
Labels: Feature, Kodi 19

#168 Update German/strings.po
  language/German/strings.po
Labels: Kodi 19, Language

#169 Finnish translation
  language/Finnish/strings.po
Labels: Kodi 19, Language

#170 [Code] cleanup, improvements
  1080i/Includes_Defs.xml
  1080i/View_500_Thumbnails.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_503_Poster_Square.xml
  1080i/View_504_Netflix.xml
  1080i/View_505_Wall_Square.xml
  1080i/View_507_Fanart.xml
  1080i/View_50_List.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_513_Shifted.xml
  1080i/View_514_Albums.xml
  1080i/View_515_SideCards.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_51_BigWide.xml
  1080i/View_520_Minimal.xml
  1080i/View_52_BigList.xml
  1080i/View_53_Poster.xml
  1080i/View_54_Banner.xml
  1080i/View_55_Wall.xml
  1080i/View_56_MediaInfo.xml
  1080i/View_57_ExtraInfo.xml
  1080i/View_58_Cards.xml
  1080i/View_59_BannerWall.xml
Labels: Improvement, Kodi 19

#171 [Indicators] percentage option added
  1080i/Includes_Labels.xml
  1080i/SkinSettings.xml
  language/English/strings.po
Labels: Feature, Kodi 19

#176 [Extended Info] hide labels if no information is available
  1080i/Includes_Defs.xml
  1080i/Includes_DialogVideoInfo.xml
Labels: Improvement, Kodi 19

#172 [DialogVideoInfo] added option to prefer local list information
  1080i/Custom_DialogSettings.xml
  1080i/Includes_Defs.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/SkinSettings.xml
  language/English/strings.po
Labels: Feature, Kodi 19

#179 [Performance] improved widgets performance
  shortcuts/template.xml
Labels: Improvement, Kodi 19

#181 Update French Language
  language/French/strings.po
Labels: Kodi 19, Language

#180 [Reflections] added reflections to home menu and views
  1080i/Home.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_NowPlaying.xml
  1080i/Includes_SubItems_Home.xml
  1080i/MyMusicNav.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/View_500_Thumbnails.xml
  1080i/View_503_Poster_Square.xml
  1080i/View_504_Netflix.xml
  1080i/View_505_Wall_Square.xml
  1080i/View_509_Shift.xml
  1080i/View_50_List.xml
  1080i/View_510_Minimal.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_513_Shifted.xml
  1080i/View_514_Albums.xml
  1080i/View_517_WallSmall.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_520_Minimal.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  1080i/View_53_Poster.xml
  1080i/View_55_Wall.xml
  1080i/View_56_MediaInfo.xml
  1080i/View_59_BannerWall.xml
  1080i/script-embuary-person.xml
  1080i/script-embuary-video.xml
  media/diffuse/listposter-ref-widgets.png
  shortcuts/template.xml
Labels: Feature, Kodi 19, Review

#183 [Views] added netflix music view
  1080i/Custom_SetMusicViewtype.xml
  1080i/Includes.xml
  1080i/Includes_Labels.xml
  1080i/MyMusicNav.xml
  1080i/View_523_Minimal_V2_Music.xml
  extras/views/523Music.jpg
Labels: Feature, Kodi 19

#188 [Code] improvements
  1080i/Includes_Defs.xml
  1080i/MusicVisualisation.xml
Labels: Improvement, Kodi 19

#189 [Widgets] added option for navigation behaviour
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
  language/English/strings.po
Labels: Improvement, Kodi 19

#192 [SkinSettings] improvements
  1080i/SkinSettings.xml
  language/English/strings.po
Labels: Improvement, Kodi 19

#191 [ViewtypeOptions] improvements
  1080i/MyMusicNav.xml
  1080i/MyVideoNav.xml
  language/English/strings.po
Labels: Improvement, Kodi 19

#194 French translate updated + minor adjustment
  language/French/strings.po
Labels: Kodi 19, Language

#196 [Netflix Preview Window] enable netflix preview window by default
  1080i/Includes.xml
  1080i/SkinSettings.xml
Labels: Improvement, Kodi 19, Review

#198 [Widgets Autoscroll, SkinSettings] improvements, minor adjustments
  1080i/SkinSettings.xml
  1080i/script-skinshortcuts.xml
  shortcuts/template.xml
Labels: Improvement, Kodi 19

#200 [SkinShortcuts] enable add/change icons by default
  1080i/script-skinshortcuts.xml
  shortcuts/overrides.xml
Labels: Feature, Kodi 19

#204 Update german language file
  language/German/strings.po
Labels: Kodi 19, Language
