Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-01, with the labels that each got.

#35 [Feature] Option to disable poster from detailed info osd (only matrix osd)
  1080i/Custom_VideoSetting.xml
  1080i/DialogSeekBar.xml
  1080i/SkinSettings.xml
  1080i/VideoOSD.xml
Labels: Feature, Kodi 19

#39 Improve OSD title width
  1080i/DialogSeekBar.xml
  1080i/Includes_Defs.xml
  1080i/Includes_OSD.xml
  1080i/VideoOSD.xml
Labels: Improvement, Kodi 19

#41 Update strings.po
  language/Korean/strings.po
Labels: Kodi 19, Language

#43 Update Includes.xml
  1080i/Includes.xml
Labels: Kodi 19, Language

#44 Update strings.po
  language/Korean/strings.po
Labels: Kodi 19, Language
