Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-03, with the labels that each got.

#109 [Improvements] Create expressions for indicators
  1080i/Includes.xml
  1080i/Includes_Images.xml
  1080i/Includes_Labels.xml
Labels: Improvement, Kodi 19

#112 [SkinSettings] Choose indicators settings
  1080i/Includes_Images.xml
  1080i/Includes_Labels.xml
  1080i/SkinSettings.xml
Labels: Kodi 19

#121 [Widgets] hopefully fixed issue with widgets navigation, when there a…
  shortcuts/template.xml
Labels: Fix, Kodi 19

#129 [Fix] added episodes content-type to view 513
  1080i/View_513_Shifted.xml
Labels: Fix, Kodi 19

#131 [Powermenu] fixed issue with reboot to android command
  1080i/Home.xml
  shortcuts/overrides.xml
  shortcuts/powermenu.DATA.xml
Labels: Fix, Kodi 19

#114 Add Release Year to View_53_Poster.xml and fix a display bug in …
  1080i/Includes_Labels.xml
Labels: Fix, Kodi 19

#133 [NowPlaying] fixed issue with nowplaying, when background image is se…
  1080i/Includes_Home.xml
Labels: Fix, Kodi 19

#139 [Homemenu Submenu] fixed issue with submenu position, when clock is d…
  1080i/Includes_Home.xml
Labels: Fix, Kodi 19

#140 [DialogVideoInfo Trakt] add to trakt watchlist button added
  1080i/Custom_DialogSettings.xml
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Labels.xml
  media/buttonsdialogs/trakt.png
Labels: Feature, Kodi 19

#141 Bugfix SkinSettings.xml Double ID
  1080i/SkinSettings.xml
Labels: Fix, Kodi 19

#142 [Background Code] changed control type from multiimage to image
  1080i/Includes.xml
Labels: Improvement, Kodi 19

#148 [SkinShortcuts] added homemenu items enabled/disabled status
  1080i/Includes_Labels.xml
  1080i/script-skinshortcuts.xml
Labels: Feature, Kodi 19

#92 add InProgressTvShows.xsp
  extras/playlists/InProgressTvShows.xsp
  shortcuts/overrides.xml
Labels: Help wanted, Kodi 19

#147 [Ratings] fixed issues with ratings
  1080i/Includes.xml
  1080i/Includes_DialogVideoInfo.xml
Labels: Fix, Kodi 19

#150 [Views] added view 521/522, similar to home netflix view
  1080i/Custom_SetViewtype.xml
  1080i/Includes.xml
  1080i/MyVideoNav.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  extras/views/521.jpg
  extras/views/522.jpg
  extras/views/light/521.jpg
  extras/views/light/522.jpg
  language/English/strings.po
Labels: Feature, Kodi 19

#152 [View 521 522] improvements
  1080i/View_521_Minimal_V2.xml
  extras/views/521.jpg
  extras/views/522.jpg
  extras/views/light/521.jpg
  extras/views/light/522.jpg
Labels: Improvement, Kodi 19

#154 [Code] cleanup, code improvements
  1080i/Includes_Home.xml
  1080i/View_500_Thumbnails.xml
  1080i/View_504_Netflix.xml
  1080i/View_509_Shift.xml
  1080i/View_510_Minimal.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_513_Shifted.xml
  1080i/View_514_Albums.xml
  1080i/View_517_WallSmall.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_520_Minimal.xml
  1080i/View_55_Wall.xml
Labels: Improvement, Kodi 19

#158 [Alternative Indicator Flags] added option to switch to alternative indicator flags
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_504_Netflix.xml
  1080i/View_507_Fanart.xml
  1080i/View_515_SideCards.xml
  1080i/View_53_Poster.xml
  1080i/View_54_Banner.xml
  1080i/View_55_Wall.xml
  1080i/View_58_Cards.xml
  1080i/script-globalsearch.xml
  language/English/strings.po
  shortcuts/template.xml
Labels: Feature, Kodi 19

#159 [DialogVideoInfo] added movies by director list to dialogvideoinfo
  1080i/Custom_DialogSettings.xml
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Defs.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_Labels.xml
  1080i/Includes_Lists.xml
  language/English/strings.po
Labels: Feature, Kodi 19
