Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-09, with the labels that each got.

#485 [Home Auto Trailer Code] improvements
  1080i/Custom_1194_AutoTrailer_Background_Helper.xml
  1080i/Custom_1195_AutoTrailer_Start_Helper.xml
  1080i/Home.xml
  1080i/Includes.xml
  1080i/Includes_Home.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/View_510_Minimal.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
Labels: Kodi 19, Improvement

#486 [Home Auto Trailer Code] much better code and performance
  1080i/Includes.xml
  1080i/MyVideoNav.xml
  1080i/VideoFullScreen.xml
  1080i/View_510_Minimal.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
Labels: Kodi 19, Improvement

#487 [Home Auto Trailer Code] improvements
  1080i/Custom_1195_AutoTrailer_Start_Helper.xml
  1080i/Custom_Overlay.xml
  1080i/Home.xml
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_CustomSettings_Items.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
  shortcuts/overrides.xml
Labels: Kodi 19, Improvement, Review

#483 [Home Auto Trailer] added auto playing trailers
  1080i/Custom_1194_AutoTrailer_Background_Helper.xml
  1080i/Custom_1195_AutoTrailer_Start_Helper.xml
  1080i/Custom_DialogCustomSettings.xml
  1080i/Custom_Overlay.xml
  1080i/DialogBusy.xml
  1080i/Home.xml
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_CustomSettings_Items.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/VideoFullScreen.xml
  1080i/View_510_Minimal.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  extras/playlists/Spotlight.xsp
  language/resource.language.en_gb/strings.po
  media/common/trailerwindow.png
Labels: Kodi 19, Feature, Review

#490 [Code] update
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
  1080i/script-skinshortcuts.xml
  shortcuts/overrides.xml
  shortcuts/template.xml
Labels: Kodi 19, Update

#488 [Widgets] improved widgets position and movement
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
  shortcuts/template.xml
Labels: Kodi 19, Feature, Review

#493 [Auto Trailer Setting] added options to pause/stop playback when info…
  1080i/DialogVideoInfo.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Improvement

#496 [Code] fixed issue with playback from dialogvideoinfo in some cases
  1080i/Includes.xml
Labels: Kodi 19, Fix

#492 [Jumpbar Views 510 521 522 523 527] added jumpbar to views
  1080i/Includes_Furniture.xml
  1080i/MyVideoNav.xml
  1080i/MyWeather.xml
  1080i/View_510_Minimal.xml
  1080i/View_520_Minimal.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  1080i/View_523_Minimal_V2_Music.xml
  1080i/View_524_Minimal_V2_Seasons.xml
  1080i/View_527_List_V2.xml
Labels: Kodi 19, Improvement

#502 [Widgets Movement] improved movement
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/View_527_List_V2.xml
  language/resource.language.en_gb/strings.po
  shortcuts/template.xml
Labels: Kodi 19, Improvement

#516 [Weather Widget] improvements
  1080i/Includes_Animations.xml
  1080i/Includes_SubItems_Home.xml
Labels: Kodi 19, Improvement, Review

#517 [FIX] behaviors displaying background on widgets 2, 3 ,4 ,5 ,6
  1080i/Includes.xml
Labels: Kodi 19, Fix, Review

#521 [Code] fixed visible condition bracket
  1080i/SkinSettings.xml
Labels: Kodi 19, Code Fix

#526 [Code] update
  1080i/DialogSeekBar.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/SkinSettings.xml
Labels: Kodi 19, Update

#527 [Home Auto Trailer] improvements to avoid trailer loop with random content widget
  1080i/Custom_1195_AutoTrailer_Start_Helper.xml
  1080i/Includes.xml
Labels: Kodi 19, Improvement

#528 [Flags] improvement display flag 3D if ".3D" in filename
  1080i/Includes_Furniture.xml
Labels: Kodi 19, Improvement

#533 Translations update from Weblate
  language/resource.language.de_de/strings.po
Labels: Kodi 19, Weblate

#529 [Code] improvements
  1080i/Custom_1297_Blur.xml
  1080i/Custom_DialogBusy.xml
  1080i/Custom_MovieDB_Movies.xml
  1080i/Custom_MovieDB_Shows.xml
  1080i/DialogBusy.xml
  1080i/Includes.xml
  1080i/Includes_Home.xml
  1080i/Includes_Lists.xml
Labels: Kodi 19, Improvement, Review

#534 [Widgets Actors] improved actor widget
  1080i/Home.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
  1080i/Includes_Lists.xml
Labels: Kodi 19, Improvement, Review

#541 [Code] update
  1080i/DialogVideoInfo.xml
  1080i/Home.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
  1080i/Includes_Lists.xml
Labels: Kodi 19, Update

#540 [Filenames] files renamed
  1080i/Custom_AutoTrailer_Background_Helper.xml
  1080i/Custom_AutoTrailer_Start_Helper.xml
  1080i/Custom_Blur.xml
  1080i/Custom_Overlay.xml
  1080i/Custom_ResetForced.xml
  1080i/Includes.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_VideoLyrics.xml
Labels: Kodi 19, Improvement

#524 [background] add option to ignore fanart embeded with addons
  1080i/Includes.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
  language/resource.language.fr_fr/strings.po
Labels: Kodi 19, Improvement

#546 [Homemenu Animation] added setting to only hide home menu if widget container gets focus
  1080i/Includes.xml
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Improvement, Review

#551 [OSD EDL Markers] added option for edl markers
  1080i/Custom_VideoSetting.xml
  1080i/Includes.xml
  1080i/Includes_OSD.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Feature, Review

#550 [DialogVideoInfo Trailer] added bingie helper script support for trailer
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_DialogMusicInfo.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_Labels.xml
Labels: Kodi 19, Improvement, Review
