Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-11, with the labels that each got.

#618 [Code] improvements, cleanup
  1080i/AddonBrowser.xml
  1080i/Custom_MusicSettings.xml
  1080i/Custom_SetMusicViewtype.xml
  1080i/Custom_SetViewtype.xml
  1080i/Custom_VideoSetting.xml
  1080i/GameOSD.xml
  1080i/Includes_Defs.xml
  1080i/Includes_PVR.xml
  1080i/MyGames.xml
  1080i/MyMusicNav.xml
  1080i/MyPics.xml
  1080i/MyPlaylist.xml
  1080i/MyPrograms.xml
  1080i/MyVideoNav.xml
  1080i/MyWeather.xml
Labels: Kodi 19, Improvement, Review

#620 [Views] changed container type from list to panel
  1080i/View_504_Netflix.xml
  1080i/View_509_Shift.xml
  1080i/View_513_Shifted.xml
  1080i/View_514_Albums.xml
  1080i/View_515_SideCards.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_527_List_V2.xml
Labels: Kodi 19, Improvement, Review

#621 [Views] changed container type from list to panel
  1080i/View_50_List.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_516_SeasonsInfo.xml
  1080i/View_524_Minimal_V2_Seasons.xml
  1080i/View_526_SeasonsInfo_V2.xml
Labels: Kodi 19, Improvement

#624 [Code] improvements, cleanup
  1080i/DialogPlayerProcessInfo.xml
Labels: Kodi 19, Improvement

#623 [OSD Bookmarks Code] improved bookmarks dialog code
  1080i/Includes_Images.xml
  1080i/VideoOSDBookmarks.xml
Labels: Kodi 19, Improvement, Review

#625 [ClearLogo Code] improvements
  1080i/Includes.xml
  1080i/Includes_DialogMusicInfo.xml
  1080i/MyVideoNav.xml
  1080i/View_504_Netflix.xml
  1080i/View_509_Shift.xml
  1080i/View_510_Minimal.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_514_Albums.xml
  1080i/View_520_Minimal.xml
  1080i/View_521_Minimal_V2.xml
Labels: Kodi 19, Improvement

#627 Translations update from Weblate
  language/resource.language.fi_fi/strings.po
  language/resource.language.zh_cn/strings.po
Labels: Kodi 19, Weblate

#630 [Indicators] added is playing indicator for reloaded indicators
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
  1080i/SkinSettings.xml
  1080i/View_500_Thumbnails.xml
  1080i/View_503_Poster_Square.xml
  1080i/View_504_Netflix.xml
  1080i/View_523_Minimal_V2_Music.xml
  1080i/View_52_BigList.xml
  1080i/View_54_Banner.xml
  1080i/View_55_Wall.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Feature, Improvement, Review

#631 [Widgets] fixed possible navigation issue
  1080i/Includes_Home.xml
Labels: Kodi 19, Fix, Review

#626 [Blur SkinSettings] added option to use embuary helper for blur
  1080i/Custom_Blur.xml
  1080i/Custom_DialogCustomSettings.xml
  1080i/Includes.xml
  1080i/Includes_CustomSettings_Items.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Feature, Improvement, Review

#635 [OSD PVR] fixed possible issue
  1080i/VideoOSD.xml
Labels: Kodi 19, Improvement

#636 Translations update from Kodi Weblate
  language/resource.language.zh_cn/strings.po
Labels: Kodi 19, Weblate
