Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-02, with the labels that each got.

#65 [ViewType] Enable View_510 for Seasons and Episodes
  1080i/Custom_SetViewtype.xml
  1080i/View_510_Minimal.xml
Labels: Improvement, Kodi 19

#74 [Home] Reduce replicated code, extending focused widget
  1080i/Includes_Home.xml
Labels: Improvement, Kodi 19

#77 Update Hun lang
  language/Hungarian/strings.po
Labels: Kodi 19, Language

#76 Update strings.po
  language/Korean/strings.po
Labels: Kodi 19, Language

#82 Add Alternative Status Overlays to View_53_Poster.xml
  1080i/MyVideoNav.xml
  1080i/View_53_Poster.xml
Labels: Feature, Kodi 19

#90 [Flags] Fix HDR condition
  1080i/Includes.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_OSD.xml
Labels: Fix, Kodi 19

#91 Make Home Widget Fade configurable, Default On
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_SubItems_Home.xml
  1080i/SkinSettings.xml
  language/English/strings.po
  language/German/strings.po
Labels: Feature, Kodi 19

#89 Code Cleanup for view53 Alternative Overlays
  1080i/View_53_Poster.xml
Labels: Improvement, Kodi 19

#87 Cd art in osd
  1080i/DialogSeekBar.xml
  1080i/SkinSettings.xml
Labels: Feature, Kodi 19

#94 Use expression for audiocodec and hdr detection
  1080i/Includes.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_OSD.xml
Labels: Improvement, Kodi 19

#97 Rename AnimatedPoster Setting furniture.animatedposters -> skinhelper…
  1080i/Includes_Images.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
Labels: Improvement, Kodi 19
