Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-05, with the labels that each got.

#208 [DialogVideoInfo] added collection info
  1080i/Custom_DialogSettings.xml
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Defs.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_Labels.xml
  language/English/strings.po
  language/French/strings.po
  language/German/strings.po
Labels: Feature, Kodi 19, Review

#210 Search from DBID if "Local info preferred"
  1080i/Includes_Defs.xml
  1080i/Includes_DialogVideoInfo.xml
Labels: Improvement, Kodi 19, Review

#211 [ExtendedInfo] added option to override play button
  1080i/Includes.xml
  1080i/Includes_Lists.xml
  1080i/SkinSettings.xml
  1080i/script-embuary-video.xml
  language/English/strings.po
Labels: Feature, Kodi 19

#216 French translate Update
  language/French/strings.po
Labels: Kodi 19, Language

#217 [View 510 DiscArt] added option to enable smaller icons and discart
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
  1080i/MyVideoNav.xml
  1080i/View_510_Minimal.xml
Labels: Feature, Kodi 19, Review

#218 [Widgets Listtype] changed list type option to select list type for each widget
  1080i/Includes_Labels.xml
  1080i/script-skinshortcuts.xml
  shortcuts/overrides.xml
  shortcuts/template.xml
Labels: Feature, Kodi 19

#219 [Code] update
  1080i/DialogExtendedProgressBar.xml
  1080i/Includes_Labels.xml
  1080i/script-skinshortcuts.xml
  shortcuts/overrides.xml
  shortcuts/template.xml
Labels: Kodi 19, Update

#220 french translate minor update
  language/French/strings.po
Labels: Kodi 19, Language

#221 [PVR Widget] added pvr vertical widgets to homemenu
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/script-skinshortcuts.xml
  language/English/strings.po
  shortcuts/overrides.xml
  shortcuts/template.xml
Labels: Feature, Kodi 19, Review

#224 [Update]
  1080i/MyVideoNav.xml
  1080i/View_521_Minimal_V2.xml
Labels: Kodi 19, Update

#222 [Homemenu Netflix ClearLogo] added clearlogo setting for netflix homemenu layout
  1080i/Includes_Home.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/View_521_Minimal_V2.xml
Labels: Feature, Kodi 19, Review

#226 Update German/strings.po
  language/German/strings.po
Labels: Kodi 19, Language

#227 [SubInfo Lines] changed sub information lines to more consistent ones
  1080i/Includes_Labels.xml
  1080i/View_514_Albums.xml
  1080i/View_521_Minimal_V2.xml
Labels: Improvement, Kodi 19, Review

#229 French translate minor adjustment
  language/French/strings.po
Labels: Kodi 19, Language

#231 [MusicVisualisation] added option to set a fallback image for music v…
  1080i/Custom_MusicSettings.xml
  1080i/MusicVisualisation.xml
  1080i/SkinSettings.xml
Labels: Feature, Kodi 19, Review

#241 french translate minor adjustment
  language/French/strings.po
Labels: Kodi 19, Language

#234 [Code] cleanup
  1080i/Includes.xml
  1080i/Includes_Images.xml
  1080i/Includes_Labels.xml
  1080i/MusicVisualisation.xml
  1080i/View_507_Fanart.xml
  shortcuts/template.xml
Labels: Improvement, Kodi 19

#242 [View Selector] improvements
  1080i/Custom_SetMusicViewtype.xml
  1080i/Custom_SetViewtype.xml
  1080i/Includes_Images.xml
  1080i/MyMusicNav.xml
  1080i/MyVideoNav.xml
Labels: Improvement, Kodi 19, Review

#239 [OSD PVR] fixed issues with thumbs
  1080i/Custom_VideoSetting.xml
  1080i/DialogSeekBar.xml
  1080i/Includes_OSD.xml
Labels: Fix, Improvement, Kodi 19, Review

#244 [Fonts] improvements, more consistency
  1080i/Font.xml
  1080i/Includes_Home.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_51_BigWide.xml
  1080i/View_58_Cards.xml
Labels: Fix, Improvement, Kodi 19, Review

#243 [Views] enable more viewtypes for "videos" content
  1080i/Custom_SetViewtype.xml
  1080i/MyVideoNav.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_504_Netflix.xml
  1080i/View_507_Fanart.xml
  1080i/View_509_Shift.xml
  1080i/View_510_Minimal.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_513_Shifted.xml
  1080i/View_514_Albums.xml
  1080i/View_515_SideCards.xml
  1080i/View_517_WallSmall.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_51_BigWide.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  1080i/View_53_Poster.xml
  1080i/View_54_Banner.xml
  1080i/View_55_Wall.xml
  1080i/View_56_MediaInfo.xml
  1080i/View_58_Cards.xml
  1080i/View_59_BannerWall.xml
Labels: Improvement, Kodi 19, Review

#245 [Background] fixed issue
  1080i/Includes.xml
Labels: Fix, Kodi 19

#246 [Update]
  1080i/Custom_MusicSettings.xml
  1080i/Custom_SetMusicViewtype.xml
  1080i/Custom_SetViewtype.xml
  1080i/Custom_VideoSetting.xml
  1080i/DialogPlayerProcessInfo.xml
  1080i/DialogSeekBar.xml
  1080i/Font.xml
  1080i/Includes.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_Home.xml
  1080i/Includes_Images.xml
  1080i/Includes_Labels.xml
  1080i/Includes_OSD.xml
  1080i/MusicVisualisation.xml
  1080i/MyMusicNav.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_502_Slider.xml
  1080i/View_504_Netflix.xml
  1080i/View_506_Slider.xml
  1080i/View_507_Fanart.xml
  1080i/View_509_Shift.xml
  1080i/View_510_Minimal.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_513_Shifted.xml
  1080i/View_514_Albums.xml
  1080i/View_515_SideCards.xml
  1080i/View_517_WallSmall.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_51_BigWide.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  1080i/View_53_Poster.xml
  1080i/View_54_Banner.xml
  1080i/View_55_Wall.xml
  1080i/View_56_MediaInfo.xml
  1080i/View_58_Cards.xml
  1080i/View_59_BannerWall.xml
  addon.xml
  changelog.txt
  extras/icons/amazon.png
  language/English/strings.po
  language/French/strings.po
  language/German/strings.po
  shortcuts/overrides.xml
  shortcuts/template.xml
Labels: Kodi 19, Update

#248 Update French translate
  language/French/strings.po
Labels: Kodi 19, Language

#252 [View 524] added view 524 for seasons
  1080i/Custom_SetViewtype.xml
  1080i/Includes.xml
  1080i/Includes_Home.xml
  1080i/Includes_Images.xml
  1080i/MyVideoNav.xml
  1080i/View_524_Minimal_V2_Seasons.xml
  extras/views/524.jpg
  extras/views/light/524.jpg
Labels: Feature, Kodi 19, Review

#253 [Furniture IMDB] added option to enable imdb position
  1080i/Custom_Ratings.xml
  1080i/Includes_Furniture.xml
  language/English/strings.po
Labels: Feature, Kodi 19, Review

#247 [NowPlaying] fixed issue with background, when no music background was found
  1080i/Includes.xml
Labels: Fix, Kodi 19, Review

#255 French Translate minor adjustment
  language/French/strings.po
Labels: Kodi 19, Language

#254 [Furniture MPAA Flags] added new colored default mpaa flags
  1080i/Custom_Ratings.xml
  1080i/Includes_Furniture.xml
  1080i/SkinSettings.xml
  language/English/strings.po
  media/flags4/flags/mpaa/australia_g.png
  media/flags4/flags/mpaa/australia_m.png
  media/flags4/flags/mpaa/australia_ma.png
  media/flags4/flags/mpaa/australia_ma15+.png
  media/flags4/flags/mpaa/australia_pg.png
  media/flags4/flags/mpaa/australia_r.png
  media/flags4/flags/mpaa/australia_r18+.png
  media/flags4/flags/mpaa/bbfc_12_certificate_uk.png
  media/flags4/flags/mpaa/bbfc_12a_certificate_uk.png
  media/flags4/flags/mpaa/bbfc_15_certificate_uk.png
  media/flags4/flags/mpaa/bbfc_18_certificate_uk.png
  media/flags4/flags/mpaa/bbfc_pg_certificate_uk.png
  media/flags4/flags/mpaa/bbfc_u_certificate_uk.png
  media/flags4/flags/mpaa/csa10.png
  media/flags4/flags/mpaa/csa12.png
  media/flags4/flags/mpaa/csa16.png
  media/flags4/flags/mpaa/csa18.png
  media/flags4/flags/mpaa/csau.png
  media/flags4/flags/mpaa/fsk-0.png
  media/flags4/flags/mpaa/fsk-12.png
  media/flags4/flags/mpaa/fsk-16.png
  media/flags4/flags/mpaa/fsk-18.png
  media/flags4/flags/mpaa/fsk-6.png
  media/flags4/flags/mpaa/g.png
  media/flags4/flags/mpaa/kr_certificate_12.png
  media/flags4/flags/mpaa/kr_certificate_15.png
  media/flags4/flags/mpaa/kr_certificate_18.png
  media/flags4/flags/mpaa/kr_certificate_all.png
  media/flags4/flags/mpaa/kr_certificate_r.png
  media/flags4/flags/mpaa/mpaa_brazil_10.png
  media/flags4/flags/mpaa/mpaa_brazil_12.png
  media/flags4/flags/mpaa/mpaa_brazil_14.png
  media/flags4/flags/mpaa/mpaa_brazil_16.png
  media/flags4/flags/mpaa/mpaa_brazil_18.png
  media/flags4/flags/mpaa/mpaa_brazil_livre.png
  media/flags4/flags/mpaa/nc-17.png
  media/flags4/flags/mpaa/nr.png
  media/flags4/flags/mpaa/pg-13.png
  media/flags4/flags/mpaa/pg.png
  media/flags4/flags/mpaa/r.png
  media/flags4/flags/mpaa/rated g.png
  media/flags4/flags/mpaa/rated nc-17.png
  media/flags4/flags/mpaa/rated nr.png
  media/flags4/flags/mpaa/rated pg.png
  media/flags4/flags/mpaa/rated r.png
  media/flags4/flags/mpaa/tv-14.png
  media/flags4/flags/mpaa/tv-g.png
  media/flags4/flags/mpaa/tv-ma.png
  media/flags4/flags/mpaa/tv-pg.png
  media/flags4/flags/mpaa/tv-y.png
  media/flags4/flags/mpaa/tv-y7.png
Labels: Feature, Kodi 19, Review

#256 [Furniture MPAA Flags] minor adjustments
  media/flags4/flags/mpaa/australia_g.png
  media/flags4/flags/mpaa/australia_m.png
  media/flags4/flags/mpaa/australia_ma.png
  media/flags4/flags/mpaa/australia_ma15+.png
  media/flags4/flags/mpaa/australia_pg.png
  media/flags4/flags/mpaa/australia_r.png
  media/flags4/flags/mpaa/australia_r18+.png
  media/flags4/flags/mpaa/csa10.png
  media/flags4/flags/mpaa/csa12.png
  media/flags4/flags/mpaa/csa16.png
  media/flags4/flags/mpaa/csa18.png
  media/flags4/flags/mpaa/csau.png
  media/flags4/flags/mpaa/g.png
  media/flags4/flags/mpaa/nc-17.png
  media/flags4/flags/mpaa/nr.png
  media/flags4/flags/mpaa/pg-13.png
  media/flags4/flags/mpaa/pg.png
  media/flags4/flags/mpaa/r.png
  media/flags4/flags/mpaa/rated g.png
  media/flags4/flags/mpaa/rated nc-17.png
  media/flags4/flags/mpaa/rated nr.png
  media/flags4/flags/mpaa/rated pg.png
  media/flags4/flags/mpaa/rated r.png
Labels: Improvement, Kodi 19
