Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-10, with the labels that each got.

#554 [Code] improvements
  1080i/AddonBrowser.xml
  1080i/Custom_MusicSettings.xml
  1080i/Custom_SetMusicViewtype.xml
  1080i/Custom_SetViewtype.xml
  1080i/Custom_VideoSetting.xml
  1080i/DialogButtonMenu.xml
  1080i/GameOSD.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_DialogMusicInfo.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_Home.xml
  1080i/Includes_Lists.xml
  1080i/Includes_PVR.xml
  1080i/MusicOSD.xml
  1080i/MyGames.xml
  1080i/MyMusicNav.xml
  1080i/MyMusicPlaylistEditor.xml
  1080i/MyPics.xml
  1080i/MyPlaylist.xml
  1080i/MyPrograms.xml
  1080i/MyVideoNav.xml
  1080i/MyWeather.xml
  1080i/View_504_Netflix.xml
  1080i/View_507_Fanart.xml
  1080i/View_513_Shifted.xml
Labels: Kodi 19, Improvement

#557 Translations update from Weblate
  language/resource.language.fr_fr/strings.po
Labels: Kodi 19, Weblate

#523 [Background] improvement if first Widget become empty
  1080i/Includes.xml
Labels: Kodi 19, Improvement, Review

#567 [Home Widgets] added pvr event icon support
  1080i/Includes_Images.xml
Labels: Kodi 19, Improvement, Review

#569 [Hub Widget] fixed issue with content type
  1080i/Includes_Defs.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Fix, Review

#571 [Code] cleanup
  1080i/Includes.xml
  1080i/Includes_Labels.xml
  1080i/Includes_OSD.xml
Labels: Kodi 19, Improvement

#581 [Home Indicators] added indicators to featured home menu
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
Labels: Kodi 19, Improvement

#616 [AutoClose OSD Code] code improvements
  1080i/Custom_AutoClose_OSD_Helper.xml
  1080i/Custom_MusicSettings.xml
  1080i/Custom_VideoSetting.xml
  1080i/DialogSelect.xml
  1080i/DialogSettings.xml
  1080i/Includes_Defs.xml
  1080i/Includes_OSD.xml
  1080i/MusicOSD.xml
  1080i/VideoOSD.xml
  1080i/VideoOSDBookmarks.xml
Labels: Kodi 19, Improvement, Review
