Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-12, with the labels that each got.

#639 [NowPlaying] improvements
  1080i/Includes_Home.xml
  1080i/Includes_NowPlaying.xml
Labels: Kodi 19, Improvement

#638 [Animations] improvements
  1080i/Includes.xml
  1080i/Includes_Animations.xml
Labels: Kodi 19, Improvement, Review

#640 [Animations] improvements
  1080i/Includes.xml
Labels: Kodi 19, Improvement

#641 [MusicVisualisation] improvements
  1080i/Custom_MusicSettings.xml
  1080i/MusicVisualisation.xml
  1080i/SkinSettings.xml
Labels: Kodi 19, Improvement, Review

#643 [Vertical Home Weather Widget] fixed issue with weather widget
  1080i/Includes_Home.xml
Labels: Kodi 19, Fix

#642 [VideoOSD] improvements
  1080i/DialogSeekBar.xml
  1080i/Includes_Animations.xml
Labels: Kodi 19, Improvement, Review

#645 [VideoOSD] improvements
  1080i/Custom_VideoSetting.xml
  1080i/DialogSeekBar.xml
  1080i/Includes_OSD.xml
  1080i/MusicVisualisation.xml
Labels: Kodi 19, Improvement

#647 [Performance] use bordertexture instead of overlay png to improve per…
  1080i/Includes.xml
  1080i/Includes_Defs.xml
Labels: Kodi 19, Improvement

#644 [Experience] improved overall experience
  1080i/Custom_Blur.xml
  1080i/Custom_Debugging.xml
  1080i/Custom_DialogCustomSettings.xml
  1080i/Custom_DialogInfoSettings.xml
  1080i/Custom_Ratings.xml
  1080i/Custom_SetHomeViewtype.xml
  1080i/Custom_VideoSetting.xml
  1080i/DialogAddonSettings.xml
  1080i/DialogButtonMenu.xml
  1080i/DialogGameControllers.xml
  1080i/DialogPVRChannelGuide.xml
  1080i/DialogPVRChannelsOSD.xml
  1080i/DialogSeekBar.xml
  1080i/DialogSelect.xml
  1080i/DialogSlider.xml
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Defs.xml
  1080i/Includes_DialogMusicInfo.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_Home.xml
  1080i/Includes_Images.xml
  1080i/Includes_Lists.xml
  1080i/Includes_NowPlaying.xml
  1080i/Includes_OSD.xml
  1080i/Includes_PVR.xml
  1080i/MusicOSD.xml
  1080i/MusicVisualisation.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/SmartPlaylistEditor.xml
  1080i/View_502_Slider.xml
  1080i/View_50_List.xml
  1080i/View_510_Minimal.xml
  1080i/View_520_Minimal.xml
  1080i/script-embuary-video.xml
  1080i/script-skinshortcuts.xml
Labels: Kodi 19, Improvement, Review

#649 [Home Animations] improvements
  1080i/Includes_Home.xml
Labels: Kodi 19, Improvement

#651 [Code] improvements
  1080i/DialogVideoInfo.xml
  1080i/Includes.xml
  1080i/Includes_Lists.xml
  media/common/bg.jpg
  media/diffuse/listposter-ref-widgets.png
Labels: Kodi 19, Improvement

#652 [Code] improvements
  1080i/Includes_Defs.xml
  1080i/SkinSettings.xml
Labels: Kodi 19, Improvement

#654 [Code] improvements
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/MusicVisualisation.xml
  1080i/SkinSettings.xml
Labels: Kodi 19, Improvement

#655 [Code] improvements, cleanup
  1080i/Custom_Overlay.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_Home.xml
  1080i/Includes_Images.xml
  1080i/MusicVisualisation.xml
  media/common/floor.png
  media/common/floor3.png
  media/common/fsinfoscreen.png
  media/common/sch2.png
Labels: Kodi 19, Improvement

#657 [OSD] improvements
  1080i/DialogSeekBar.xml
  1080i/Includes.xml
  1080i/Includes_OSD.xml
  1080i/MusicVisualisation.xml
  1080i/VideoOSD.xml
Labels: Kodi 19, Improvement

#658 [OSD] improvements
  1080i/DialogSeekBar.xml
  1080i/Includes_OSD.xml
  1080i/MusicVisualisation.xml
  1080i/VideoOSD.xml
Labels: Kodi 19, Improvement

#656 [Code, Animations] improvements
  1080i/DialogSeekBar.xml
  1080i/Includes.xml
  1080i/Includes_OSD.xml
  1080i/MusicVisualisation.xml
  1080i/VideoOSD.xml
Labels: Kodi 19, Improvement

#659 [Code] improvements, cleanup
  1080i/DialogSeekBar.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/MyVideoNav.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_507_Fanart.xml
  1080i/View_510_Minimal.xml
  1080i/View_515_SideCards.xml
  1080i/View_51_BigWide.xml
  1080i/View_520_Minimal.xml
  1080i/View_53_Poster.xml
  1080i/View_54_Banner.xml
  1080i/View_58_Cards.xml
  media/misc/overlaywatched.png
Labels: Kodi 19, Improvement

#660 [OSD] improvements
  1080i/DialogSeekBar.xml
Labels: Kodi 19, Improvement

#663 [Music OSD] show seekbar, when player is seeking, forwarding, ...
  1080i/MusicVisualisation.xml
Labels: Kodi 19, Improvement

#662 [OSD] improvements, rework
  1080i/Custom_VideoSetting.xml
  1080i/DialogSeekBar.xml
  1080i/Includes_Animations.xml
  1080i/Includes_OSD.xml
  1080i/MusicVisualisation.xml
  1080i/VideoOSD.xml
Labels: Kodi 19, Improvement

#665 Translations update from Kodi Weblate
  language/resource.language.fr_fr/strings.po
  language/resource.language.zh_cn/strings.po
Labels: Kodi 19, Weblate

#667 [Visualisation] fixed possible issue, when visualisation in the background is enabled, but no visualisation is set
  1080i/Includes.xml
  1080i/Includes_Home.xml
Labels: Kodi 19, Fix, Review

#668 [Home Now Playing Visualisation] added scrolling text option for now …
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/SkinSettings.xml
Labels: Kodi 19, Feature

#672 [DialogVideoInfo] added just watch icon
  1080i/Includes_Defs.xml
  1080i/Includes_DialogVideoInfo.xml
  media/misc/just_watch_icon.png
Labels: Kodi 19

#673 [Code] cleanup
  1080i/Includes_Defs.xml
  shortcuts/template.xml
Labels: Kodi 19, Improvement

#675 [Background Animations] improvements
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/SkinSettings.xml
Labels: Kodi 19, Improvement

#677 [Views] cleanup, minor adjustments
  1080i/Includes_PVR.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_50_List.xml
  1080i/View_515_SideCards.xml
  1080i/View_56_MediaInfo.xml
  1080i/View_57_ExtraInfo.xml
Labels: Kodi 19, Improvement

#678 [Views 501 507] code improvements, cleanup
  1080i/Includes.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_507_Fanart.xml
Labels: Kodi 19, Improvement

#680 [Animations] improvements
  1080i/Includes_Animations.xml
  1080i/Includes_Home.xml
  1080i/Includes_NowPlaying.xml
Labels: Kodi 19, Improvement, Review

#682 [Textures] cleanup
  1080i/DialogNotification.xml
  1080i/DialogVolumeBar.xml
  1080i/Includes.xml
  1080i/Includes_DialogMusicInfo.xml
  1080i/MyWeather.xml
  media/common/border.png
  media/common/box11.png
  media/common/box12.png
  media/common/box13.png
  media/common/box14.png
  media/common/box15.png
  media/common/box15white.png
  media/common/box16.png
  media/common/box17.png
  media/common/box17white.png
  media/common/box18.png
  media/common/box19.png
  media/common/box2.png
  media/common/box20.png
  media/common/box20white.png
  media/common/box21.png
  media/common/box3.png
  media/common/box3white.png
  media/common/box4.png
  media/common/box5.png
  media/common/box6.png
  media/common/box7.png
  media/common/box8.png
  media/common/box8white.png
  media/common/nofocus-shadow10.png.bak
Labels: Kodi 19, Improvement

#683 [Textures] cleanup
  1080i/View_501_Modern_Fanart.xml
  1080i/View_507_Fanart.xml
  media/bgpanel.png
  media/common/background.png
  media/globalsearch-black.png
  media/globalsearch-header.png
  media/globalsearch-overlay.jpg
  media/globalsearch-separator.png
  media/globalsearch-shadow.png
  media/globalsearch-thumbnail-focus.png
  media/globalsearch-white.png
  media/inner.png
  media/misc/bild2inlay.png
  media/misc/server.png
  media/misc/server_connect.png
  media/misc/serveroffline.png
  media/misc/serveronline.png
  media/panel.png
  media/panel_trans.png
  media/poster.png
  media/separator.png
  media/server.png
  media/server_connect.png
  media/serveroffline.png
  media/serveronline.png
  media/sun.png
  shortcuts/overrides.xml
Labels: Kodi 19, Improvement

#684 [Textures] cleanup
  themes/Square/common/as.png
  themes/Square/common/background.png
  themes/Square/common/bg.jpg
  themes/Square/common/bg.png
  themes/Square/common/box11.png
  themes/Square/common/box12.png
  themes/Square/common/box13.png
  themes/Square/common/box14.png
  themes/Square/common/box15.png
  themes/Square/common/box15white.png
  themes/Square/common/box16.png
  themes/Square/common/box17.png
  themes/Square/common/box17white.png
  themes/Square/common/box18.png
  themes/Square/common/box19.png
  themes/Square/common/box2.png
  themes/Square/common/box20white.png
  themes/Square/common/box21.png
  themes/Square/common/box3.png
  themes/Square/common/box3white.png
  themes/Square/common/box4.png
  themes/Square/common/box5.png
  themes/Square/common/box6.png
  themes/Square/common/box7.png
  themes/Square/common/box8.png
  themes/Square/common/box8white.png
  themes/Square/common/fsinfoscreen.png
  themes/Square/common/whitetest.png
Labels: Kodi 19, Improvement
