Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2021-06, with the labels that each got.

#257 [Fix] - Log error - unmatched parentheses
  1080i/Includes_Labels.xml
Labels: Fix, Kodi 19

#260 [Fix] - Label hard coded
  1080i/Custom_SetViewtype.xml
Labels: Improvement, Kodi 19

#261 [Fix] - Label code kodi. Must be code label AZR
  1080i/Custom_SetMusicViewtype.xml
  1080i/Custom_SetViewtype.xml
  1080i/Includes_Labels.xml
Labels: Improvement, Kodi 19

#262 [Label ViewType] Improvement and consistancy
  1080i/Custom_SetViewtype.xml
  1080i/View_520_Minimal.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  1080i/View_55_Wall.xml
  language/English/strings.po
  language/Finnish/strings.po
  language/French/strings.po
  language/German/strings.po
  language/Hungarian/strings.po
  language/Italian/strings.po
  language/Korean/strings.po
  language/Spanish/strings.po
Labels: Improvement, Kodi 19, Review

#263 [Views 510 520] added option to use default selectbox size
  1080i/MyVideoNav.xml
  1080i/View_510_Minimal.xml
  1080i/View_520_Minimal.xml
  language/English/strings.po
Labels: Feature, Kodi 19, Review

#251 [Fix] #157 - HomeMenu Background
  1080i/Includes.xml
Labels: Fix, Improvement, Kodi 19, Review

#265 [Localization] - French translate - minor adjustment
  language/French/strings.po
Labels: Kodi 19, Language

#269 [Update]
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
  1080i/script-skinshortcuts.xml
  language/English/strings.po
  shortcuts/overrides.xml
Labels: Kodi 19, Update

#267 [Widgets] added option to enable smaller fanart/thumbs
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
  1080i/script-skinshortcuts.xml
  language/English/strings.po
  shortcuts/overrides.xml
Labels: Feature, Kodi 19, Review

#270 readd 94f1ac996c0eb6f150d99f53f22a16c58c8ca3a4
  language/English/strings.po
  language/German/strings.po
Labels: Kodi 19, Language

#271 [Widgets] added new viewtype poster/thumb
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
  language/English/strings.po
  shortcuts/overrides.xml
Labels: Feature, Kodi 19, Review

#274 [Artwork Beef] readd support for artwork.beef
  1080i/Includes.xml
Labels: Feature, Kodi 19

#276 [Addon Beef] display only if addon is enable
  1080i/Includes.xml
Labels: Improvement, Kodi 19

#275 [Localization] French translate
  language/French/strings.po
Labels: Kodi 19, Language

#280 [Update]
  1080i/Custom_1297_Blur.xml
  1080i/Includes.xml
Labels: Kodi 19, Update

#277 [Background Brightness] added setting for background brightness
  1080i/Custom_1297_Blur.xml
  1080i/Home.xml
  1080i/Includes.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_Labels.xml
  1080i/SkinSettings.xml
  colors/Darker.xml
  colors/Darkest.xml
  colors/Light Brown.xml
  colors/Light.xml
  colors/defaults.xml
Labels: Feature, Kodi 19, Review

#282 [UpNext] added option to use thumbnail instead fanart
  1080i/Includes_Images.xml
  1080i/SkinSettings.xml
  1080i/script-upnext-stillwatching-simple.xml
  1080i/script-upnext-stillwatching.xml
  1080i/script-upnext-upnext-simple.xml
  1080i/script-upnext-upnext.xml
  language/English/strings.po
Labels: Improvement, Kodi 19, Review

#283 update German/strings.po
  language/German/strings.po
Labels: Kodi 19, Language

#284 [Localization] French Translate
  language/French/strings.po
Labels: Kodi 19, Language

#291 [Fix] check all brackets duplicate or missing in all XML
  1080i/Custom_MusicSettings.xml
  1080i/DialogPlayerProcessInfo.xml
  1080i/Includes.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/MyWeather.xml
  1080i/View_510_Minimal.xml
  1080i/service-LibreELEC-Settings-mainWindow.xml
Labels: Fix, Improvement, Kodi 19

#287 [Fix] ERROR "GetDirectory - Error getting noop" in LOG
  1080i/Includes_Defs.xml
Labels: Fix, Improvement, Kodi 19

#295 [Background] fix
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Home.xml
Labels: Fix, Improvement, Kodi 19

#296 [Background] fix 2
  1080i/Home.xml
  1080i/Includes.xml
Labels: Fix, Improvement, Kodi 19

#299 [Homemenu Viewtype Clean] lots of improvements
  1080i/Includes.xml
  1080i/Includes_Home.xml
  1080i/Includes_SubItems_Home.xml
Labels: Improvement, Kodi 19, Update

#297 [Fix] Weather Widget not display at startup
  shortcuts/template.xml
Labels: Fix, Kodi 19

#301 [Language Fix] patch-1
  1080i/Custom_DialogSettings.xml
  1080i/Custom_Ratings.xml
  1080i/Custom_SetViewtype.xml
  1080i/Includes_Labels.xml
  1080i/MyVideoNav.xml
  1080i/SkinSettings.xml
  1080i/View_50_List.xml
  1080i/View_526_SeasonsInfo_V2.xml
  language/English/strings.po
  language/French/strings.po
  language/German/strings.po
  language/Hungarian/strings.po
  language/Italian/strings.po
  shortcuts/overrides.xml
Labels: Fix, Kodi 19, Language

#302 [Localization] French minor fix
  language/French/strings.po
Labels: Fix, Kodi 19, Language

#294 [Homemenu Viewtype Clean] added new homemenu viewtype
  1080i/Custom_SetHomeViewtype.xml
  1080i/Home.xml
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
  1080i/SkinSettings.xml
  1080i/script-skinshortcuts.xml
  extras/homemenu/9.jpg
  language/English/strings.po
  media/common/floor2.png
  shortcuts/template.xml
Labels: Feature, Kodi 19, Review

#305 [Homemenu Items Clean] added items count to clean and minimal home me…
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
Labels: Feature, Kodi 19, Review

#303 [Home Multi Netflix] option to hide info Widget when focus Home Menu
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
  language/English/strings.po
  language/French/strings.po
Labels: Feature, Kodi 19

#306 [Localization] Fench translate updated
  language/French/strings.po
Labels: Kodi 19, Language

#266 [Viewtypelist] move "Poster wall small" under "Poster wall" in list Viewtype
  1080i/Custom_SetViewtype.xml
Labels: Improvement, Kodi 19, Review

#307 [Furniture] added audiostreams info
  1080i/Custom_Ratings.xml
  1080i/Includes.xml
  1080i/Includes_Furniture.xml
  language/English/strings.po
Labels: Feature, Kodi 19

#308 [Animations Homemenu] improved home menu animations
  1080i/Custom_SetHomeViewtype.xml
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Defs.xml
  shortcuts/template.xml
Labels: Improvement, Kodi 19, Review

#309 [Code] improvements
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
Labels: Improvement, Kodi 19

#311 [Weather Widgets] hopefully fixed issue with weather widget background
  1080i/Includes.xml
Labels: Fix, Kodi 19

#312 [Code] improvements, cleanup
  1080i/Custom_1297_Blur.xml
  1080i/DialogConfirm.xml
  1080i/DialogNotification.xml
  1080i/DialogPVRChannelGuide.xml
  1080i/DialogPVRChannelsOSD.xml
  1080i/DialogSeekBar.xml
  1080i/DialogSlider.xml
  1080i/DialogVolumeBar.xml
  1080i/Includes.xml
  1080i/Includes_DialogPVRInfo.xml
  1080i/Includes_OSD.xml
  1080i/MusicOSD.xml
  1080i/MusicVisualisation.xml
  1080i/SettingsCategory.xml
  1080i/Startup.xml
  1080i/script-embuary-person.xml
  1080i/script-embuary-video.xml
Labels: Improvement, Kodi 19

#313 [Background] fixed issue with brightness, when clean home menu is ena…
  1080i/Includes.xml
Labels: Fix, Kodi 19, Review

#317 [Scrollbar] Option to hide scrollbar for more views (Flix v2)
  1080i/Includes_Furniture.xml
  1080i/MyVideoNav.xml
  1080i/View_510_Minimal.xml
  1080i/View_520_Minimal.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_522_Minimal_V2_Episodes.xml
  1080i/View_523_Minimal_V2_Music.xml
  1080i/View_524_Minimal_V2_Seasons.xml
Labels: Improvement, Kodi 19, Review

#293 [MENU] Underlined items vertical multi widgets homemenu
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
  media/common/underline2.png
Labels: Feature, Kodi 19, Review

#318 [Bugfix] Netflix fullsize fanart
  1080i/Includes.xml
Labels: Fix, Kodi 19

#319 [Background] patch-4
  1080i/Includes_Defs.xml
Labels: Fix, Kodi 19

#320 [LibreElec] Fix Improve LibreElecSettings MainWindows
  1080i/service-LibreELEC-Settings-mainWindow.xml
Labels: Fix, Improvement, Kodi 19

#322 [LibreElec] design fit to AZR
  1080i/service-LibreELEC-Settings-mainWindow.xml
Labels: Feature, Improvement, Kodi 19

#323 [CoreElec] Minor adjustement + fix code deprecated
  1080i/service-CoreELEC-Settings-mainWindow.xml
  1080i/service-LibreELEC-Settings-mainWindow.xml
Labels: Improvement, Kodi 19

#324 little search and replace fix
  1080i/service-CoreELEC-Settings-mainWindow.xml
Labels: Improvement, Kodi 19

#326 [Improvement] display icon libreelec and coreelec in list
  shortcuts/overrides.xml
Labels: Feature, Kodi 19

#327 [Feature] add all others icons + cleaning : space end line, tab at beginning of line
  shortcuts/overrides.xml
Labels: Improvement, Kodi 19

#325 [Colorbox Blur] added option to use colorbox script for blur
  1080i/Custom_1297_Blur.xml
  1080i/Includes.xml
  1080i/Includes_BlurSettings.xml
  1080i/Includes_Defs.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
  language/resource.language.en_gb/strings.po
Labels: Feature, Kodi 19, Review

#329 [code] Old Infobool deprecated
  1080i/script-skin_helper_service-ColorPicker.xml
  1080i/service-CoreELEC-Settings-mainWindow.xml
  1080i/service-LibreELEC-Settings-mainWindow.xml
  shortcuts/powermenu.DATA.xml
  shortcuts/template.xml
Labels: Code Fix, Improvement, Kodi 19

#331 [SkinSettings Colorbox] improvements
  1080i/Custom_DialogCustomSettings.xml
  1080i/Includes_BlurSettings.xml
  1080i/Includes_CustomSettings_Items.xml
Labels: Improvement, Kodi 19

#333 [Furniture Icons] fixed possible issue when clock is disabled
  1080i/Includes_Defs.xml
  1080i/Includes_Furniture.xml
Labels: Improvement, Kodi 19

#335 [Clearlogo] Fix clearlogo position top position for Modern Widgets
  1080i/Includes_Furniture.xml
  1080i/View_521_Minimal_V2.xml
Labels: Improvement, Kodi 19, Review

#341 [DialogVideoInfo] added option to enable additional artwork
  1080i/Custom_DialogSettings.xml
  1080i/DialogVideoInfo.xml
  1080i/Includes.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_Images.xml
  language/resource.language.en_gb/strings.po
Labels: Feature, Kodi 19

#334 [Background] fixed possible issue when extended now playing is enable…
  1080i/Includes.xml
Labels: Fix, Kodi 19, Review

#345 [SkinSettings Blur] improvements to blur settings dialog
  1080i/Custom_1297_Blur.xml
  1080i/Includes_BlurSettings.xml
  1080i/Includes_Defs.xml
  1080i/script-skin_helper_service-ColorPicker.xml
Labels: Improvement, Kodi 19

#339 [SkinSettings] improvements rework
  1080i/Custom_1297_Blur.xml
  1080i/Includes_Defs.xml
  1080i/SettingsCategory.xml
  1080i/SkinSettings.xml
  language/resource.language.de_de/strings.po
  language/resource.language.en_gb/strings.po
  language/resource.language.es_es/strings.po
  language/resource.language.fi_fi/strings.po
  language/resource.language.fr_fr/strings.po
  language/resource.language.hu_hu/strings.po
  language/resource.language.it_it/strings.po
  language/resource.language.ko_kr/strings.po
Labels: Improvement, Kodi 19, Review

#342 [SkinSettings Colors Theme] added wip option to remember skin theme/c…
  1080i/SettingsCategory.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
  language/resource.language.en_gb/strings.po
Labels: Feature, Kodi 19, Review

#348 DiscArt minor adjustment (Show now playing info)
  1080i/Includes_NowPlaying.xml
Labels: Improvement, Kodi 19

#349 [Code] improved performance when using clean and minimal home menu
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  shortcuts/template.xml
Labels: Improvement, Kodi 19

#347 [Homemenu Indicators] added watched indicators to clean home menu
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
Labels: Feature, Kodi 19, Review

#350 [Code] improvements
  1080i/Includes_Defs.xml
Labels: Improvement, Kodi 19
