Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2022-02, with the labels that each got.

#741 [Animated Artwork] added support for animated artwork module
  1080i/SkinSettings.xml
  1080i/Startup.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Feature, Review

#744 [Textbox Dialogs] reset autoscroll position
  1080i/Custom_Reset_Textbox_Helper.xml
  1080i/Includes_DialogAddonInfo.xml
  1080i/Includes_DialogMusicInfo.xml
  1080i/Includes_DialogPVRInfo.xml
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_OSD.xml
Labels: Kodi 19, Improvement, Review

#750 [NowPlaying] improved consistency
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/MusicVisualisation.xml
Labels: Kodi 19, Improvement, Review

#752 Translations update from Kodi Weblate
  language/resource.language.es_es/strings.po
Labels: Kodi 19, Weblate

#753 [Star Rating Music] improvements to music rating
  1080i/Includes_OSD.xml
  media/osd/rating_new.png
Labels: Kodi 19, Improvement

#754 [NowPlaying] added option to choose artwork type for music
  1080i/Includes_Images.xml
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/SkinSettings.xml
Labels: Kodi 19, Feature, Review

#760 [Next Recording Information] fixed possible issue in some cases
  1080i/Includes_Home.xml
Labels: Kodi 19, Improvement, Fix

#763 [NowPlaying Controls] added fullscreen button, added always visible option
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/Includes_OSD.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Improvement, Review

#767 [Views] fixed info for linked movies
  1080i/Includes_Labels.xml
Labels: Kodi 19, Improvement, Review

#768 [Code] cleanup
  1080i/Custom_VideoSetting.xml
  1080i/Includes_Labels.xml
  1080i/SkinSettings.xml
  1080i/script-skinshortcuts.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Improvement

#772 [Code] improved performance
  1080i/Includes.xml
  1080i/Includes_Animations.xml
  1080i/Includes_Custom_Items.xml
  1080i/Includes_Lists.xml
  shortcuts/template.xml
Labels: Kodi 19, Improvement, Review

#773 [Code] improvements, cleanup
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  shortcuts/overrides.xml
  shortcuts/template.xml
Labels: Kodi 19, Improvement, Review

#774 [Code] improved skin shortcuts configuration
  1080i/Includes_Labels.xml
  1080i/script-skinshortcuts.xml
Labels: Kodi 19, Improvement

#778 [SkinSettings ClearLogo] improved clearlogo settings
  1080i/Home.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Improvement

#783 [Widgets] improved widget info line
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
Labels: Kodi 19, Improvement
