Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2022-10, with the labels that each got.

#860 [HomeNextRecording] added option to hide next recording dialog
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Kodi 19, Improvement

#859 [Views] Added extended gamemode views
  1080i/Custom_SetViewtype.xml
  1080i/GameOSD.xml
  1080i/Includes.xml
  1080i/Includes_Games.xml
  1080i/Includes_Images.xml
  1080i/Includes_Labels.xml
  1080i/MyGames.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_503_Poster_Square.xml
  1080i/View_504_Netflix.xml
  1080i/View_505_Wall_Square.xml
  1080i/View_507_Fanart.xml
  1080i/View_509_Shift.xml
  1080i/View_50_List.xml
  1080i/View_510_Minimal.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_513_Shifted.xml
  1080i/View_514_Albums.xml
  1080i/View_515_SideCards.xml
  1080i/View_517_WallSmall.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_51_BigWide.xml
  1080i/View_521_Minimal_V2.xml
  1080i/View_527_List_V2.xml
  1080i/View_53_Poster.xml
  1080i/View_54_Banner.xml
  1080i/View_55_Wall.xml
  1080i/View_56_MediaInfo.xml
  1080i/View_57_ExtraInfo.xml
  1080i/View_58_Cards.xml
  1080i/View_59_BannerWall.xml
  language/resource.language.en_us/strings.po
Labels: Kodi 19, Feature, Improvement, Review

#841 [DialogKeyboard] improvements
  1080i/DialogKeyboard.xml
  1080i/Includes.xml
Labels: Kodi 19, Improvement, Review

#864 Feature/game furniture
  1080i/Includes_Furniture.xml
  1080i/Includes_Games.xml
  1080i/Includes_Labels.xml
  1080i/MyGames.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
  language/resource.language.en_us/strings.po
  media/flags/empty_fallback.png
Labels: Kodi 19, Improvement, Review

#868 [Genre/Studio Icons] added studio and genre icons support
  1080i/Includes_Defs.xml
  1080i/Includes_Images.xml
  1080i/View_50_List.xml
  shortcuts/overrides.xml
Labels: Kodi 19, Improvement, Review
