Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2023-03, with the labels that each got.

#928 [Views] improvements
  1080i/Includes_Labels.xml
  1080i/View_51_BigWide.xml
Labels: Improvement, Kodi 20

#931 [Fix] Widgets fade animation disable don't works for "system info" and "settings" widgets
  1080i/Includes_SubItems_Home.xml
Labels: Fix, Kodi 20

#932 [Views] fixed issue with duration in some cases
  1080i/Includes_Defs.xml
  1080i/Includes_Furniture.xml
Labels: Fix, Kodi 20

#935 [MusicVisualisation] improvements to lyrics and background
  1080i/Includes.xml
  1080i/Includes_Lyrics.xml
  1080i/MusicVisualisation.xml
Labels: Improvement, Kodi 20

#937 [Indicators] fixed issue
  1080i/Includes.xml
  1080i/Includes_Labels.xml
Labels: Fix, Kodi 20

#939 [SkinSettings Colors] fixed issue with color palette
  1080i/SkinSettings.xml
  1080i/Startup.xml
Labels: Fix, Kodi 20

#942 [MusicVisualisation] fixed issue with lyrics
  1080i/Includes_Lyrics.xml
Labels: Fix, Kodi 20

#940 Translations update from Kodi Weblate
  language/resource.language.et_ee/strings.po
  language/resource.language.it_it/strings.po
  language/resource.language.ru_ru/strings.po
Labels: Weblate, Kodi 20

#949 [DialogVideoInfo] add click on button info to open TMDb info
  1080i/Includes.xml
Labels: Feature, Kodi 20

#948 [Media Flags] code improvements and cleanup
  1080i/Includes_DialogVideoInfo.xml
  1080i/Includes_Furniture.xml
  1080i/Includes_Labels.xml
  language/resource.language.de_de/strings.po
Labels: Improvement, Kodi 20

#945 [Code] skin settings cleanup
  1080i/Includes_Defs.xml
  1080i/SettingsCategory.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
Labels: Improvement, Kodi 20

#955 [StarRating] match osd star rating color
  1080i/Custom_DialogCustomSettings.xml
  1080i/Custom_ResetColors.xml
  1080i/Custom_SaveColorConfiguration.xml
  1080i/Includes_Custom_Items.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Improvement, Kodi 20

#956 [Indicators] added option to show label for tv shows if tv show is in…
  1080i/Includes_Labels.xml
  1080i/SkinSettings.xml
Labels: Improvement, Kodi 20
