Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2023-02, with the labels that each got.

#916 [Flag] WEB-DL / WEBRIP improvement
  1080i/Includes_Furniture.xml
Labels: Improvement, Kodi 20

#915 [Flag] codec audio video improvement
  1080i/Includes.xml
Labels: Improvement, Kodi 20

#917 [Indicators] added tv show status
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
Labels: Feature, Improvement, Review, Kodi 20

#812 [Widgets Background Episodes] added setting to use thumb instead of fanart for background on episodes
  1080i/Includes.xml
  1080i/SkinSettings.xml
  language/resource.language.en_gb/strings.po
Labels: Feature, Improvement, Review, Kodi 20

#921 [Artwork] strings update
  1080i/Includes_Labels.xml
  language/resource.language.en_gb/strings.po
  shortcuts/overrides.xml
Labels: Fix, Kodi 20

#918 [Indicators] improvements
  1080i/Custom_MovieDB_Movies.xml
  1080i/Custom_MovieDB_Shows.xml
  1080i/Includes.xml
  1080i/View_501_Modern_Fanart.xml
  1080i/View_504_Netflix.xml
  1080i/View_507_Fanart.xml
  1080i/View_509_Shift.xml
  1080i/View_511_Double.xml
  1080i/View_512_Double_Banner.xml
  1080i/View_513_Shifted.xml
  1080i/View_517_WallSmall.xml
  1080i/View_519_Shift_Modern.xml
  1080i/View_51_BigWide.xml
  1080i/View_53_Poster.xml
  1080i/View_55_Wall.xml
  1080i/View_59_BannerWall.xml
Labels: Improvement, Review, Kodi 20

#922 [SkinShortcuts] strings update
  1080i/Includes_Images.xml
  1080i/Includes_Labels.xml
  language/resource.language.en_gb/strings.po
  shortcuts/overrides.xml
Labels: Fix, Kodi 20
