Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2023-01, with the labels that each got.

#900 [SettingsCategory] improvements
  1080i/SettingsCategory.xml
Labels: Improvement, Kodi 20

#881 Add season number to Wide episodes view
  1080i/Includes_Labels.xml
  1080i/View_54_Banner.xml
Labels: Kodi 19, Kodi 20

#903 Translations update from Kodi Weblate
  language/resource.language.es_mx/strings.po
  language/resource.language.hu_hu/strings.po
  language/resource.language.ko_kr/strings.po
  language/resource.language.nl_nl/strings.po
  language/resource.language.pl_pl/strings.po
  language/resource.language.pt_br/strings.po
  language/resource.language.pt_pt/strings.po
  language/resource.language.tr_tr/strings.po
  language/resource.language.zh_cn/strings.po
Labels: Language, Weblate

#906 [View 50] added play count for music to view 50
  1080i/Includes_Labels.xml
  1080i/View_50_List.xml
Labels: Improvement, Kodi 20

#908 [ScreenCalibration] fixed issue
  1080i/SettingsScreenCalibration.xml
  media/other_textures/reset.png
Labels: Fix, Kodi 20
