Repository beatmasterRS/skin.arctic.zephyr.mod, pull requests merged in 2023-04, with the labels that each got.

#957 [NowPlaying Info] added info action
  1080i/Custom_NowPlaying_Stop_Helper.xml
  1080i/DialogMusicInfo.xml
  1080i/DialogVideoInfo.xml
  1080i/Includes.xml
  1080i/Includes_NowPlaying.xml
  1080i/Includes_OSD.xml
Labels: Feature, Kodi 20

#960 [NowPlaying] added next songs play function for music
  1080i/Custom_NowPlaying_Stop_Helper.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/Includes_OSD.xml
Labels: Feature, Kodi 20

#962 [DialogMusicInfo] typo fix
  1080i/Includes_DialogMusicInfo.xml
Labels: Fix, Kodi 20

#963 [DialogMusicInfo] improvement - extended Artist Fanart for Item Album
  1080i/Includes.xml
  1080i/Includes_DialogMusicInfo.xml
Labels: Improvement, Kodi 20

#964 [Code] improvements, cleanup
  1080i/Includes_Defs.xml
  1080i/Includes_DialogAddonInfo.xml
  1080i/Includes_DialogMusicInfo.xml
  1080i/Includes_DialogPVRInfo.xml
Labels: Improvement, Kodi 20

#965 [Music] changed playlists to kodi default setting track artist title
  1080i/Includes_NowPlaying.xml
  1080i/MusicOSD.xml
Labels: Improvement, Kodi 20

#966 [NowPlaying] improved skip controls
  1080i/Custom_NowPlaying_Stop_Helper.xml
  1080i/Includes.xml
Labels: Improvement, Kodi 20

#968 [NowPlaying] removed player controls on up option
  1080i/Custom_NowPlaying_AutoClose_Controls_Helper.xml
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
Labels: Improvement, Kodi 20

#970 [NowPlaying] improved next track list onclick action
  1080i/Includes_NowPlaying.xml
Labels: Improvement, Kodi 20

#971 [NowPlaying Helper] improved nowplaying helper code
  1080i/Custom_NowPlaying_AutoShow_Helper.xml
  1080i/Custom_NowPlaying_Helper.xml
  1080i/Custom_NowPlaying_Stop_Helper.xml
  1080i/Custom_Overlay.xml
  1080i/Home.xml
  1080i/Includes.xml
  1080i/Includes_Defs.xml
  1080i/Includes_Home.xml
  1080i/Includes_NowPlaying.xml
Labels: Improvement, Kodi 20

#974 [Views FileSize] added filesize to list views
  1080i/Custom_Overlay.xml
  1080i/Includes_Labels.xml
  1080i/View_50_List.xml
Labels: Improvement, Review, Kodi 20

#981 [Code] update
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/View_50_List.xml
Labels: Update, Kodi 20

#978 [NowPlaying] enable nowplaying controls by default, removed misplaced info line
  1080i/Includes.xml
  1080i/Includes_Home.xml
  1080i/Includes_Labels.xml
  1080i/Includes_NowPlaying.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
Labels: Improvement, Kodi 20

#911 IMDB rating
  1080i/Custom_Ratings.xml
  1080i/Includes_Furniture.xml
  media/misc/imdb.png
  media/misc/imdb_white.png
Labels: Feature, Review, Kodi 20

#982 [Startup] changed first start skin settings
  1080i/Startup.xml
Labels: Improvement, Kodi 20

#987 [Home SlideOut] changed slide out home menu behaviour
  1080i/Includes_Home.xml
  1080i/SkinSettings.xml
  1080i/Startup.xml
  language/resource.language.en_gb/strings.po
Labels: Improvement, Kodi 20

#989 [NowPlaying] focus controls instead main menu (2)
  1080i/Custom_NowPlaying_Helper.xml
  1080i/Includes_NowPlaying.xml
Labels: Improvement, Kodi 20

#990 [NowPlaying CleanAndMinimal] fixed animation
  1080i/Includes_Home.xml
  1080i/Includes_NowPlaying.xml
  shortcuts/template.xml
Labels: Improvement, Kodi 20

#992 [NowPlaying Animations] improved dics art animations
  1080i/Includes_NowPlaying.xml
Labels: Improvement, Kodi 20

#993 [Addon] version bump to 2.0.3
  addon.xml
  changelog.txt
Labels: Kodi 20, Version
